# Generated by Django 4.1.5 on 2023-02-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurultai', '0002_alter_comment_options_alter_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birth_of_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='account',
            name='birth_of_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='account',
            name='living_place',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Место проживания'),
        ),
        migrations.AddField(
            model_name='account',
            name='nation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Нация'),
        ),
        migrations.AddField(
            model_name='account',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Номер телефона'),
        ),
    ]
